# Generated by Django 3.0.8 on 2020-08-02 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_subjectcell_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='no_of_lec',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(14)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectcell',
            name='period',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(14)]),
        ),
    ]
