# Generated by Django 3.0.8 on 2020-08-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_subject_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cells',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.SubjectCell'),
        ),
    ]
