# Generated by Django 3.0.8 on 2020-08-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200804_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cells',
        ),
        migrations.AddField(
            model_name='subjectcell',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='timetable.Subject'),
            preserve_default=False,
        ),
    ]
